<?php
use yii\bootstrap\Nav;

/* @var $this yii\web\View */
$this->title = 'Karate';
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="col-md-2 site-nav">
        <?= Nav::widget([
            'items' => [
                ['label' => 'Mitgliedschaft', 'url' => ['site/page']],
                ['label' => 'Vorstand', 'url' => ['site/page']],
                ['label' => 'Über uns', 'url' => ['site/page']],
                ['label' => 'Geschichte', 'url' => ['site/page']],
            ],
        ]); ?>
    </div>

    <div class="col-md-9 site-text">
        <h1>Karate</h1>
        <p>Karate [kaɺate] Karate?/i (jap. 空手, dt. „leere Hand“) ist eine Kampfkunst, deren Geschichte sich sicher bis ins Okinawa des 19. Jahrhunderts zurückverfolgen lässt, wo einheimische okinawanische Traditionen (Ti) mit chinesischen (Shàolín Quánfǎ) Einflüssen zum Tōde verschmolzen. Zu Beginn des 20. Jahrhunderts fand dieses seinen Weg nach Japan und wurde nach dem Zweiten Weltkrieg von dort als Karate über die ganze Welt verbreitet.</p>
        <p>Inhaltlich wird Karate vor allem durch Schlag-, Stoß-, Tritt- und Blocktechniken sowie Fußfegetechniken als Kern des Trainings charakterisiert. Einige wenige Hebel und Würfe werden (nach ausreichender Beherrschung der Grundtechniken) ebenfalls gelehrt, im fortgeschrittenen Training werden auch Würgegriffe und Nervenpunkttechniken geübt. Manchmal wird die Anwendung von Techniken unter Zuhilfenahme von Kobudōwaffen geübt, wobei das Waffentraining kein integraler Bestandteil des Karate ist.</p>
        <p>Recht hoher Wert wird meistens auf die körperliche Kondition gelegt, die heutzutage insbesondere Beweglichkeit, Schnellkraft und anaerobe Belastbarkeit zum Ziel hat. Die Abhärtung der Gliedmaßen u. a. mit dem Ziel des Bruchtests (jap. Tameshiwari), also des Zerschlagens von Brettern oder Ziegeln, ist heute weniger populär, wird aber von Einzelnen immer noch betrieben. </p>
        <p>Das moderne Karate-Training ist häufig eher sportlich orientiert. Das heißt, dass dem Wettkampf eine große Bedeutung zukommt. Diese Orientierung wird häufig kritisiert, da man glaubt, dass dadurch die Vermittlung effektiver Selbstverteidigungstechniken, die durchaus zum Karate gehören, eingeschränkt wird und das Karate verwässert.</p>

        <h2>Geschichte</h2>
        <h3>Name</h3>
        <p>Karatedō (japanisch „Weg der leeren Hand“) wurde früher meist nur als Karate bezeichnet und ist unter dieser Bezeichnung noch heute am häufigsten geführt. Der Zusatz dō wird verwendet, um den philosophischen Hintergrund der Kunst und ihre Bedeutung als Lebensweg zu unterstreichen. Bis in die 1930er-Jahre hinein war die Schreibweise 唐手 gebräuchlich, was wörtlich „chinesische Hand“ bedeutet. Das Schriftzeichen 唐 mit der sino-japanischen Lesung tō und der japanischen Lesung kara bezog sich auf das China der Tang-Dynastie (618 bis 907 n. Chr.). Damit waren die chinesischen Ursprünge bereits im Namen der Kampfkunst manifestiert. Aus vermutlich politischen Gründen (Nationalismus) ging man dann in Japan dazu über, die Schreibung 空手, also „leere Hand“, zu verwenden. Das neue Zeichen wurde wie das alte kara gelesen und war auch von der Bedeutung her insofern passend, als im Karate meist mit leeren Händen, also ohne Waffen, gekämpft wird.</p>
        <p>Im Deutschen ist bei der Aussprache des Wortes Karate eine Betonung der zweiten Silbe verbreitet. Oft wird sogar wie in mehreren romanischen Sprachen, zum Beispiel im Französischen oder Portugiesischen, auf te betont. Nach der japanischen Aussprache des Wortes dagegen ist eine gleichwertige Akzentuierung jeder Silbe üblich.</p>

        <h3>Ursprünge</h3>
        <p>Die Legende erzählt, dass der buddhistische Mönch Daruma Taishi (Bodhidharma) aus Kanchipuram (Südindien) im 6. Jahrhundert das Kloster Shaolin (jap. Shōrinji) erreicht und dort nicht nur den Ch'an (Zen)-Buddhismus begründet, sondern die Mönche auch in körperlichen Übungen unterwiesen habe, damit sie das lange Meditieren aushalten konnten. So sei das Shaolin Kung Fu (korrekt: Shaolin-Quánfǎ, jap. Kempō/Kenpō) entstanden, aus dem sich dann viele andere chinesische Kampfkunststile (Wushu) entwickelt hätten.</p>
        <p>Da Karate um seine chinesischen Wurzeln weiß, betrachtet es sich ebenfalls gerne als Nachfahren jener Tradition (Chan, Bodhidharma, Shaolin), deren Historizität im Dunkeln liegt und unter Historikern umstritten ist. Trotzdem ziert das Bildnis von Daruma so manches Dōjō.</p>

        <h3>Von China nach Okinawa</h3>
        <p>Karate in seiner heutigen Form entwickelte sich auf der pazifischen Kette der Ryūkyū-Inseln, insbesondere auf der Hauptinsel Okinawa. Diese liegt ca. 500 Kilometer südlich der japanischen Hauptinsel Kyūshū zwischen Südchinesischem Meer und Pazifik. Heute ist die Insel Okinawa ein Teil der gleichnamigen Präfektur Japans. Bereits im 14. Jahrhundert unterhielt Okinawa, damals Zentrum des unabhängigen Inselkönigreichs Ryūkyū, rege Handelskontakte zu Japan, China, Korea und Südostasien.</p>
        <p>Die urbanen Zentren der Insel, Naha, Shuri und Tomari, waren damals wichtige Umschlagplätze für Waren und boten damit ein Forum für den kulturellen Austausch mit dem chinesischen Festland. Dadurch gelangten erste Eindrücke chinesischer Kampftechniken des Quánfǎ/Kempō nach Okinawa, wo sie sich mit dem einheimischen Kampfsystem des Te/De (Ryūkyū-Dialekt Tī) vermischten und sich so zum Tōde (Tōdī) oder Okinawa-Te (Uchinādī - „Hand aus Okinawa“) weiterentwickelten. Te bedeutet wörtlich „Hand“, im übertragenen Sinne auch „Technik“ bzw. „Handtechnik“. Der ursprüngliche Begriff für Tōde oder Karate (jap. 唐手) kann daher frei als „Handtechnik aus dem Land der Tang“ (China) übersetzt werden (bedeutet aber natürlich die verschiedenen Techniken als Ganzes).</p>
        <p>Die unterschiedliche wirtschaftliche Bedeutung der Inseln führte dazu, dass sie ständig von Unruhen und Aufständen heimgesucht wurden. Im Jahre 1422 gelang es schließlich König Sho Hashi, die Inseln zu einen. Zur Erhaltung des Friedens in der aufständischen Bevölkerung verbot er daraufhin das Tragen jeglicher Waffen. Seit 1477 regierte sein Nachfolger Shō Shin und bekräftigte die Politik des Waffenverbotes seines Vorgängers. Um die einzelnen Regionen zu kontrollieren, verpflichtete er sämtliche Fürsten zum dauerhaften Aufenthalt an seinen Hof in Shuri – eine Kontrollmöglichkeit, die später von den Tokugawa-Shogunen kopiert wurde. Durch das Waffenverbot erfreute sich die waffenlose Kampfkunst des Okinawa-Te erstmals wachsender Beliebtheit, und viele ihrer Meister reisten nach China, um sich dort durch das Training des chinesischen Quánfǎ fortzubilden.</p>
        <p>1609 besetzten die Shimazu aus Satsuma die Inselkette und verschärften das Waffenverbot dahingehend, dass sogar der Besitz jeglicher Waffen, selbst Zeremonienwaffen, unter schwere Strafe gestellt wurde. Dieses Waffenverbot wurde als Katanagari („Jagd nach Schwertern“) bezeichnet. Schwerter, Dolche, Messer und jegliche Klingenwerkzeuge wurden systematisch eingesammelt. Dies ging sogar soweit, dass einem Dorf nur ein Küchenmesser zugestanden wurde, das mit einem Seil an den Dorfbrunnen (oder an einer anderen zentralen Stelle) befestigt und streng bewacht wurde.</p>
        <p>Das verschärfte Waffenverbot sollte Unruhen und bewaffnete Widerstände gegen die neuen Machthaber unterbinden. Jedoch hatten japanische Samurai das Recht der sogenannten „Schwertprobe“, dem zufolge sie die Schärfe ihrer Schwertklinge an Leichen, Verwundeten oder auch willkürlich an einem Bauern erproben konnten, was auch vorkam. Die Annexion führte somit zu einer gesteigerten Notwendigkeit zur Selbstverteidigung, zumal damals auf dem feudalen Okinawa Polizeiwesen und Rechtsschutz fehlten, die den einzelnen vor solchen Eingriffen schützen konnten. Der Mangel an staatlichen Rechtsschutzinstitutionen und die gesteigerte Wehrnotwendigkeit vor Willkürakten der neuen Machthaber begründeten also einen Intensivierungs- und Subtilisierungsprozess des Kampfsystems Te zur Kampfkunst Karate.</p>
        <p>Ungefähr zwanzig Jahre dauerte es, bis sich die großen Meister des Okinawa-Te zu einem geheimen oppositionellen Bund zusammenschlossen und festlegten, dass Okinawa-Te nur noch im Geheimen an ausgesuchte Personen weitergegeben werden sollte.</p>
        <p>Währenddessen entwickelte sich in der bäuerlich geprägten Bevölkerung das Kobudō, das Werkzeuge und Alltagsgegenstände mit seinen speziellen Techniken zu Waffen verwandelte. Dabei gingen spirituelle, mentale und gesundheitliche Aspekte, wie sie im Chuan-Fa gelehrt wurden, verloren. Auf Effizienz ausgelegt, wurden Techniken, die unnötiges Risiko bargen, wie beispielsweise Fußtritte im Kopfbereich, nicht trainiert. So lässt sich in diesem Zusammenhang von einer Auslese der Techniken sprechen. Kobudō und seine aus Alltagsgegenständen und Werkzeugen hergestellten Waffen konnten schon aus wirtschaftlichen Gründen nicht verboten werden, da sie für die Versorgung der Bevölkerung sowie der Besatzer schlicht notwendig waren.</p>
        <p>Allerdings war es sehr schwer, mit diesen Waffen einem ausgebildeten und gut bewaffneten Krieger im Kampf gegenüberzutreten. Deshalb entwickelte sich in Okinawa-Te und Kobudō, die damals noch eng miteinander verknüpft gelehrt wurden, die Maxime, möglichst nicht getroffen zu werden und gleichzeitig die wenigen Gelegenheiten, die sich boten, zu nutzen, den Gegner mit einem einzigen Schlag zu töten. Dieses für das Karate spezifische Prinzip heißt Ikken hissatsu. Die Auslese von möglichst effizienten Kampftechniken und das Ikken-Hissatsu-Prinzip brachten dem Karate den ungerechtfertigten Ruf ein, ein aggressives Kampfsystem, ja sogar die „Härteste aller Kampfsportarten“ zu sein (siehe dazu weiter unten Film und Medien).</p>
        <p>Die tödliche Wirkung dieser Kampfkunst führte dazu, dass die japanischen Besatzer erneut das Verbot ausdehnten, und das Lehren von Okinawa-Te ebenfalls unter drakonische Strafe stellten. Allerdings wurde es weiterhin im Geheimen unterrichtet. Damit wurde die Kenntnis des Te für lange Zeit auf kleine elitäre Schulen oder einzelne Familien beschränkt, da die Möglichkeit zum Studium der Kampfkünste auf dem chinesischen Festland nur wenigen begüterten Bürgern zur Verfügung stand.

        <h3>Matsumura</h3>
        <p>Weil die Kunst des Schreibens in der Bevölkerung damals kaum verbreitet war, und man aus Geheimhaltungsgründen dazu gezwungen war, wurden keinerlei schriftliche Aufzeichnungen angefertigt, wie das in chinesischen Kung-Fu-Stilen manchmal der Fall war (siehe Bubishi). Man verließ sich auf die mündliche Überlieferung und die direkte Weitergabe. Zu diesem Zweck bündelten die Meister die zu lehrenden Kampftechniken in didaktischen zusammenhängenden Einheiten zu festgelegten Abläufen oder Formen. Diese genau vorgegebenen Abläufe werden als Kata bezeichnet. Um dem Geheimhaltungszweck der Okinawa-Te Rechnung zu tragen, mussten diese Abläufe vor Nicht-Eingeweihten der Kampfschule (also vor potenziellen Ausspähern) chiffriert werden. Dabei bediente man sich als Chiffrierungscode der traditionellen Stammestänze (odori), die den systematischen Aufbau der Kata beeinflussten. So besitzt jede Kata noch bis heute ein strenges Schrittdiagramm (Embusen). Die Effizienz der Chiffrierung der Techniken in Form einer Kata zeigt sich bei der Kata-Demonstration vor Laien: Für den Laien und in den ungeübten Augen des Karate-Anfängers muten die Bewegungen befremdlich oder nichtssagend an. Die eigentliche Bedeutung der Kampfhandlungen erschließt sich einem erst durch intensives Kata-Studium und der „Dechiffrierung“ des Kata. Dies erfolgt im Bunkai-Training. Eine Kata ist also ein traditionelles, systematisches Kampfhandlungsprogramm und das hauptsächliche Medium der Tradition des Karate.</p>
        <p>Der erste noch namentlich bekannte Meister des Tōde war vermutlich Chatan Yara, der etliche Jahre in China lebte und dort die Kampfkunst seines Meisters erlernte. Der Legende nach unterrichtete er wohl „Tōde“ Sakugawa, einen Schüler von Peichin Takahara. Auf Sakugawa geht eine Variante der Kata Kushanku, benannt nach einem chinesischen Diplomaten, zurück. Der bekannteste Schüler Sakugawas war „Bushi“ Matsumura Sōkon, der später sogar den Herrscher von Okinawa unterrichtete.</p>
    </div>
